# Generated by Django 4.2.1 on 2023-05-12 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=119)),
                ("redirect_urls", models.TextField()),
                ("client_id", models.CharField(max_length=40, unique=True)),
                ("client_secret", models.CharField(max_length=64)),
            ],
        ),
    ]
